services:
  highload-db:
    image: postgres:15-alpine
    container_name: highload-db
    environment:
      POSTGRES_DB: highload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - highload_db_data:/var/lib/postgresql/data
    networks:
      - highload-network

  user-accounter-db:
    image: postgres:15-alpine
    container_name: user-accounter-db
    environment:
      POSTGRES_DB: user-accounter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - user_accounter_db_data:/var/lib/postgresql/data
    networks:
      - highload-network

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - highload-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - highload-network
    depends_on:
      - highload-db
      - config-server

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - highload-network

  app:
    build: ./main
    container_name: highload-app
    environment:
      DB_URL: jdbc:postgresql://highload-db:5432/highload
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8082:8082"
    depends_on:
      - highload-db
      - config-server
      - eureka-server
    networks:
      - highload-network

  user-service:
    build: ./user-accounter
    container_name: highload-user-accounter
    networks:
      - highload-network
    ports:
      - "8081:8081"
    depends_on:
      - highload-db
      - config-server
      - eureka-server

volumes:
  highload_db_data:

  user_accounter_db_data:

networks:
  highload-network:
    driver: bridge