services:
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - highload-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  highload-db:
    image: postgres:15-alpine
    container_name: highload-db
    environment:
      POSTGRES_DB: highload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - highload_db_data:/var/lib/postgresql/data
    networks:
      - highload-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d highload" ]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - highload-network
    depends_on:
      highload-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - highload-network

  app:
    build: ./main
    container_name: highload-app
    environment:
      DB_URL: jdbc:postgresql://highload-db:5432/highload
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8082:8082"
    depends_on:
      highload-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - highload-network

  user-accounter:
    build: ./user-accounter
    container_name: highload-user-accounter
    networks:
      - highload-network
    ports:
      - "8081:8081"
    depends_on:
      - highload-db
      - config-server
      - eureka-server

volumes:
  highload_db_data:

networks:
  highload-network:
    driver: bridge