services:
  highload-db:
    image: postgres:15-alpine
    container_name: highload-db
    environment:
      POSTGRES_DB: highload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - highload_db_data:/var/lib/postgresql/data
    networks:
      - highload-network

  app:
    build: ./main
    container_name: highload-app
    environment:
      DB_URL: jdbc:postgresql://highload-db:5432/highload
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - highload-db
    networks:
      - highload-network

  user-service:
    build: ./user-accounter
    container_name: highload-user-accounter
    networks:
      - highload-network
    ports:
      - "8080:8080"
    depends_on:
      - highload-db
#      - config-server
#      - eureka-server
#      - postgres

volumes:
  highload_db_data:

networks:
  highload-network:
    driver: bridge